Add support for iGPU

diff --git a/applications/qwen2_5_vl_3b_local/Dockerfile b/applications/qwen2_5_vl_3b_local/Dockerfile
--- a/applications/qwen2_5_vl_3b_local/Dockerfile
+++ b/applications/qwen2_5_vl_3b_local/Dockerfile
@@ -17,6 +17,7 @@
 # limitations under the License.
 
 ARG BASE_IMAGE
+ARG GPU_TYPE
 
 FROM ${BASE_IMAGE} AS base
 
@@ -33,10 +34,29 @@ RUN echo ". /etc/bash_completion.d/holohub_autocomplete" >> /etc/bash.bashrc
 
 ARG CMAKE_BUILD_TYPE=Release
 
+ARG GPU_TYPE
+ARG CUDA_MAJOR
+RUN INDEX_URL=""; \
+    if [ "${GPU_TYPE}" = "igpu" ]; then \
+        apt-get update && \
+        apt-get install -y --reinstall --no-install-recommends \
+            libcudnn9-cuda-12 \
+            libcudnn9-dev-cuda-12 && \
+        rm -rf /var/lib/apt/lists/* && \
+        python3 -m pip list | grep -i torch | awk '{print $1}' | xargs -r python3 -m pip uninstall -y && \
+        INDEX_URL="https://pypi.jetson-ai-lab.io/jp6/cu126"; \
+    elif [ "${CUDA_MAJOR}" = "12" ]; then \
+        INDEX_URL="https://download.pytorch.org/whl/cu124"; \
+    elif [ "${CUDA_MAJOR}" = "13" ]; then \
+        INDEX_URL="https://download.pytorch.org/whl/cu130"; \
+    else \
+        echo "Error: Unsupported GPU_TYPE (${GPU_TYPE}) or CUDA_MAJOR (${CUDA_MAJOR})" && exit 1; \
+    fi \
+    && python3 -m pip install --no-cache-dir setuptools \
+    && python3 -m pip install --no-cache-dir torch torchvision --index-url ${INDEX_URL}
+
 COPY applications/qwen2_5_vl_3b_local/requirements.txt /tmp/requirements.txt
 RUN sed -i '/holoscan/d' /tmp/requirements.txt
-RUN python3 -m pip install --no-cache-dir setuptools && \
-    python3 -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cu124 && \
-    python3 -m pip install -r /tmp/requirements.txt --no-cache-dir
+RUN python3 -m pip install -r /tmp/requirements.txt --no-cache-dir
 
 WORKDIR /workspace/holohub
